---
sudo: required

language: python
python: "2.7"

branches:
  only:
    - master

before_install:
  - sudo apt-get update

install:
  - pip install ansible

script:
  - ansible-playbook -i hosts install.yml
