---
# hosts could have been "remote" or "all" as well
- hosts: local
  connection: local
  name: Get started playbook
  become: yes

  tasks:
    - name: Install vim
      dnf:
        name: vim
        state: latest
    - name: Install Powerline
      dnf:
        name: powerline
        state: latest
      notify:
        - Install powerline-fonts
    - name: Install vim-powerline
      dnf:
        name: vim-powerline
        state: latest
      notify:
        - Configure vim-powerline

  handlers:
    - name: Install powerline-fonts
      dnf:
        name: powerline-fonts
        state: present
    - name: Configure vim-powerline
      blockinfile:
        path: '/home/{{ ansible_user }}/.vimrc'
        create: yes
        insertafter: EOF
        content: |
          python3 from powerline.vim import setup as powerline_setup
          python3 powerline_setup()
          python3 del powerline_setup
          set laststatus=2 " Always display the statusline in all windows
          set showtabline=2 " Always display the tabline, even if there is only one tab
          set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
          set t_Co=256
