---
# hosts could have been "remote" or "all" as well
- hosts: local
  connection: local
  name: Get started playbook
  become: yes
  vars:
    - packages:
        - vim
        - xclip

  tasks:
    - name: Install updates for Fedora system
      dnf:
        name=*
        state=latest
      when: ansible_distribution == "Fedora"

    - name: Install Packages
      dnf:
        name: "{{item}}"
        state: latest
      with_items:
        - "{{packages}}"

    - name: Install Powerline
      dnf:
        name: powerline
        state: latest
      notify:
        - Install powerline-fonts

    - name: Install vim-powerline
      dnf:
        name: vim-powerline
        state: latest
      notify:
        - Configure vim-powerline

    - name: Enable chrome repo
      template:
        src={{ playbook_dir }}/templates/google-chrome.repo.j2
        dest=/etc/yum.repos.d/google-chrome.repo
        owner=root
        group=root
        mode=0644

  handlers:
    - name: Install powerline-fonts
      dnf:
        name: powerline-fonts
        state: present
    - name: Configure vim-powerline
      blockinfile:
        path: '/home/{{ ansible_user }}/.vimrc'
        create: yes
        insertafter: EOF
        content: |
          python3 from powerline.vim import setup as powerline_setup
          python3 powerline_setup()
          python3 del powerline_setup
          set laststatus=2 " Always display the statusline in all windows
          set showtabline=2 " Always display the tabline, even if there is only one tab
          set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
          set t_Co=256
